# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='asset_logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=50)),
                ('image_x', models.IntegerField(max_length=20)),
                ('image_y', models.IntegerField(max_length=20)),
                ('logo_x', models.IntegerField(max_length=20)),
                ('logo_y', models.IntegerField(max_length=20)),
                ('strings', models.CharField(max_length=200)),
                ('strings_x', models.CharField(max_length=200)),
                ('strings_y', models.CharField(max_length=200)),
            ],
        ),
    ]
