# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0002_asset_image_asset_logo_creative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'images/', verbose_name=b'Label')),
            ],
        ),
    ]
