# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='email',
            field=models.CharField(default=b'rp493@cornell.edu', max_length=30),
        ),
    ]
