# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0004_photo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
