# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0005_auto_20160724_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
