# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0006_auto_20160724_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=b'/CraftCloud/FostPost/fostpost_app/static/images_uploaded/', verbose_name=b'Label'),
        ),
    ]
