# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import fostpost_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0007_auto_20160724_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(storage=fostpost_app.models.OverwriteStorage(), upload_to=b'/CraftCloud/FostPost/fostpost_app/static/images_uploaded/', verbose_name=b'Label'),
        ),
    ]
