# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0008_auto_20160907_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftcloud_user',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
