# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import fostpost_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0010_auto_20160923_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(storage=fostpost_app.models.OverwriteStorage(), upload_to=b'/home/ec2-user/FostPost_OpenStack/fostpost_app/media/', verbose_name=b'Label'),
        ),
    ]
