# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-13 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import fostpost_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fostpost_app', '0011_auto_20161002_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(storage=fostpost_app.models.OverwriteStorage(), upload_to=b'http://fostpostmedia.s3.amazonaws.com/', verbose_name=b'Label'),
        ),
    ]
