branch-defaults:
  AngularJS_Branch:
    environment: fostpost-sean-dev
    group_suffix: null
global:
  application_name: fostpost_sean
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
